version: '3.0'

services:
  frontend:
    image: ghcr.io/zarraozaga/bootcamp-gds-frontend:c682bf77d971f4755b0d019617f8c56f43088332
    command: "npm start"
    environment:
      NODE_ENV: development
      APP_URL: http://localhost:3000
      API_URL: http://backend:3001
    ports:
      - 3000:3000
  
  backend:
    image: ghcr.io/zarraozaga/bootcamp-gds-backend:c682bf77d971f4755b0d019617f8c56f43088332
    command: "npm start"
    environment:
      NODE_ENV: development
      APP_URL: http://localhost:3000
      API_URL: http://localhost:3001
      PORT: 3001
    ports:
      - 3001:3001
